service: python-lambda-api-service

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - .idea/**

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: src/handlers/hello.main
    events:
      - httpApi:
          method: GET
          path: '/hello/{name}'
      - httpApi:
          method: GET
          path: '/hello'

  debug:
    handler: src/handlers/debug.main
    events:
      - httpApi:
          method: GET
          path: /debug

  catchAll:
    handler: src/handlers/404.main
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux